# Generated by Django 4.2.3 on 2023-07-21 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Branch', models.CharField(default='Jemo', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Photo', models.ImageField(default='cust-photos/mine.jpg', upload_to='cust-photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Batch_Number', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Unit_Price', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1)),
                ('branch', models.CharField(default='Lebu', max_length=255)),
                ('Total', models.IntegerField(default=0)),
                ('time_diff', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='unknown', max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='drug_images/')),
                ('Batch_Number', models.CharField(max_length=100)),
                ('Category', models.CharField(default='Cosmotics', max_length=100)),
                ('Expired_Date', models.DateTimeField()),
                ('Days', models.IntegerField(default=1)),
                ('exdate', models.IntegerField(default=1)),
                ('Unit_Price', models.IntegerField()),
                ('Description', models.TextField(max_length=255)),
                ('Branch', models.CharField(default='Jemo', max_length=255)),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recv_name', models.CharField(max_length=255)),
                ('send_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='temp_bill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('Quant', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profile_photo')),
                ('tele', models.IntegerField(default='0988372717')),
                ('branch', models.CharField(choices=[('Head Office', 'Head Office'), ('Lebu', 'Lebu'), ('Jemo', 'Jemo')], default='Head Office', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, default=2000.0, max_digits=8)),
                ('position', models.CharField(choices=[('System Admin', 'System Admin'), ('Super Druggist', 'Super Druggist'), ('Pharmacist', 'Pharmacist'), ('Druggist', 'Druggist'), ('Cashier', 'Cashier'), ('Customer', 'Customer')], default='Customer', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
