# Generated by Django 4.2.3 on 2023-08-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WBPMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
