# Generated by Django 4.2.3 on 2024-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBPMS', '0004_medicine_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='LebuMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='drug_images/')),
                ('Batch_Number', models.CharField(max_length=100)),
                ('Category', models.CharField(default='Cosmotics', max_length=100)),
                ('Expired_Date', models.DateTimeField()),
                ('Days', models.IntegerField(default=1)),
                ('exdate', models.IntegerField(default=1)),
                ('Unit_Price', models.IntegerField()),
                ('Description', models.TextField(max_length=255)),
                ('Branch', models.CharField(default='Jemo', max_length=255)),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
