# Generated by Django 4.2.3 on 2024-04-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBPMS', '0005_lebumedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='jemomedicine',
            name='Selector',
            field=models.IntegerField(default=0),
        ),
    ]
