# Generated by Django 4.2.3 on 2024-04-21 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WBPMS', '0008_alter_profile_tele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tele',
            field=models.PositiveIntegerField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +2519... or +2517...', regex='^\\+?1?\\d{9,15}$'), django.core.validators.MaxLengthValidator]),
        ),
    ]
